"""Schema definitions for generated TSV files."""

from __future__ import annotations

ADVISOR_HEADERS = [
    "run_id",
    "as_of_date",
    "scope_mode",
    "record_type",
    "source_system",
    "source_id",
    "recommendation_type_id",
    "advisor_recommendation_id",
    "advisor_metadata_id",
    "service_name",
    "retiring_feature",
    "retirement_date",
    "days_to_retirement",
    "months_to_retirement",
    "retirement_date_quality",
    "subscription_id",
    "subscription_name",
    "resource_id",
    "resource_name",
    "resource_group",
    "resource_type",
    "location",
    "tags_json",
    "environment_hint",
    "platform_hint",
    "impact",
    "risk",
    "category",
    "sub_category",
    "platform_state",
    "last_updated",
    "label",
    "short_description_problem",
    "short_description_solution",
    "description",
    "potential_benefits",
    "learn_more_link",
    "action_link",
    "action_caption",
    "description_quality",
    "join_quality",
    "diagnostic_flags",
    "provenance_json",
    "raw_json",
]

SERVICE_HEALTH_HEADERS = [
    "run_id",
    "as_of_date",
    "scope_mode",
    "record_type",
    "source_system",
    "source_id",
    "event_id",
    "tracking_id",
    "event_type",
    "event_sub_type",
    "event_source",
    "event_level",
    "level",
    "status",
    "priority",
    "title",
    "summary",
    "description",
    "recommended_actions",
    "impact_start_time",
    "impact_mitigation_time",
    "last_update_time",
    "date_for_window",
    "impacted_service",
    "impacted_service_guid",
    "impacted_region",
    "subscription_id",
    "subscription_name",
    "resource_granularity",
    "resource_id",
    "resource_group",
    "resource_type",
    "is_sensitive",
    "details_fetch_status",
    "description_quality",
    "diagnostic_flags",
    "provenance_json",
]

DIAGNOSTICS_HEADERS = [
    "run_id",
    "severity",
    "check_id",
    "source_system",
    "scope",
    "observed_count",
    "expected_count",
    "message",
    "action_required",
    "raw_context_json",
]

AGGREGATE_HEADERS = [
    "impacted_platforms",
    "impacted_subscriptions",
    "impacted_platforms_subscriptions_json",
    "advice_type",
    "advisory_key",
    "technology_or_service",
    "retiring_feature",
    "action_required",
    "retirement_date",
    "retirement_date_quality",
    "priority_label",
    "source_systems",
    "source_identifiers",
    "source_links",
    "summary_text",
    "details_text",
    "first_seen_date",
    "last_seen_date",
]

SLIDE_HEADERS = [
    "platforms",
    "platforms_subscriptions_json",
    "priority_label",
    "advice_type",
    "technology_or_service",
    "retiring_feature",
    "action_required",
    "retirement_date",
    "source_links",
]
