# general
env_short = "d"
env       = "dev"
location  = "northeurope"

tags = {
  CreatedBy   = "Terraform"
  Environment = "Dev"
  Owner       = "UserRegistry"
  Source      = "https://github.com/pagopa/userregistry-infra"
  CostCenter  = "TS310 - PAGAMENTI & SERVIZI"
}

lock_enable = false

# 🔐 key vault
key_vault_name    = "usrreg-d-kv-neu"
key_vault_rg_name = "usrreg-d-sec-rg-neu"

keyvault_autogenerated_secrets = [
  "postgres-user-registry-user-password",
  "postgres-monitoring-user-password",
  "postgres-monitoring-external-user-password"
]

keyvault_raw_secrets = [
  {
    name  = "postgres-user-registry-user-login",
    value = "usrreg"
    type  = "username"
  }
]

# ☁️ networking
cidr_vnet                 = ["10.1.0.0/16"]
cidr_subnet_appgateway    = ["10.1.128.0/24"]
cidr_subnet_postgres      = ["10.1.129.0/24"]
cidr_subnet_azdoa         = ["10.1.130.0/24"]
cidr_subnet_cosmosdb      = ["10.1.131.0/24"]
cidr_subnet_vpn           = ["10.1.133.0/24"]
cidr_subnet_dns_forwarder = ["10.1.134.0/29"]
cidr_subnet_apim          = ["10.1.136.0/24"]
cidr_subnet_k8s           = ["10.1.0.0/17"]

# dns
dns_zone_prefix = "dev.userregistry"
external_domain = "pagopa.it"

# azure devops
enable_azdoa        = true
enable_iac_pipeline = true

# ❇️ app_gateway
app_gateway_sku_name             = "Standard_v2"
app_gateway_sku_tier             = "Standard_v2"
app_gateway_alerts_enabled       = false
app_gateway_waf_enabled          = false
app_gateway_api_certificate_name = "api-dev-userregistry-pagopa-it"

# postgres
postgres_private_endpoint_enabled      = false
postgres_sku_name                      = "B_Gen5_1"
postgres_public_network_access_enabled = false
postgres_network_rules = {
  ip_rules = [
    "0.0.0.0/0"
  ]
  # dblink
  allow_access_to_azure_services = false
}

# cosmosdb
cosmosdb_byok_enabled             = false
cosmosdb_first_setup_byok         = false
cosmosdb_extra_capabilities       = ["EnableServerless"]
cosmosdb_private_endpoint_enabled = false

#
# 🗺 APIM
#
apim_publisher_name                = "PagoPA SelfCare DEV"
apim_sku                           = "Developer_1"
apim_api_internal_certificate_name = "api-internal-dev-userregistry-pagopa-it"

#
# ⛴ AKS
#
aks_private_cluster_enabled = false
aks_alerts_enabled          = false
# This is the k8s ingress controller ip. It must be in the aks subnet range.
reverse_proxy_ip        = "10.1.0.250"
aks_max_pods            = 100
aks_enable_auto_scaling = false
aks_node_min_count      = null
aks_node_max_count      = null
aks_vm_size             = "Standard_B4ms"
